### ISSUE TITLE
Project를 어떻게 편집하는지요?

### ISSUE THREAD

**Issue by happyjem** [kaki104/diablo3hub#4]
Project 에 Task를 Create하거나 변경하려고 해도 권한이 없는 듯 한데, 이 부분은 어떻게 해야 하는지 약간 자세히 Guide 부탁드립니다.

**Comment by kaki104** [comment]
음..권한이 없군요..저도 처음이라 가능한줄 알았습니다. 콜라보레이터에 추가했습니다~
이제 가능하지 않을까요?

**Comment by happyjem** [comment]
예. 권한 문제인것 같네요. 이제 편집할 수 있게 된것 같습니다.
