### ISSUE TITLE
다음과 같은 Error Message 에 대해 알고 싶습니다.

### ISSUE THREAD

**Issue by happyjem** [kaki104/diablo3hub#5]
Build를 해보면 BattleTagPage.xaml 에서 다음과 같은 Error Message 가 나옵니다. 

"the text associated with this error code could not be found ... the text associated with this error code could not be found the attached property 'Behavior' was not found in type 'interaction' "

그리고 Clear build 후 build Target 을 ARM 으로 바꾸고 Build 다시 Target 을 X64 로 바꾸면 Error Message 는  

"the text associated with this error code could not be found ... the text associated with this error code could not be found. collection property '__implict_item' is null " 로 나옵니다. 다시 build 하면 첫번쨰 Error messgae 가 나오고요.  

물론 앱을 실행하는 데는 문제가 없습니다.

참고 이미지

![img_1199](https://cloud.githubusercontent.com/assets/42398/26334434/0a0889fa-3fa0-11e7-9801-c46a13f1c92d.jpg)
![img_1200](https://cloud.githubusercontent.com/assets/42398/26334436/0a5d72a8-3fa0-11e7-80c6-a00c793f3121.jpg)

**Comment by kaki104** [comment]
일반적으로 xaml프로젝트는 디자인시에 x86을 선택하고 작업을 합니다 저도 x64 로 지정하면 위와같은 오류 보입니다
